# Site settings
title: ryan_code
email: mcbrideryan89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Engineering Blog
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://ryanmcbri.de" # the base hostname & protocol for your site
twitter_username: NullOfUndefined
github_username: Ryan-McBride

# Build settings
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
