# Site settings
title: ryan_code
email: mcbrideryan89@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Development Blog
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://ryancode.ninja" # the base hostname & protocol for your site
twitter_username: I_Am_Not_Char
github_username: Ryan-McBride

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]